name: Gauri
favicon: null
layout_spectrum: 0.782952707959339
typography_spectrum: 0.8357325668912381
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4007006448227912
  lightness: 0.14739176887087524
  saturation: 0.2713225993793458
  rhythmicContrast: 0.8080173884518445
purpose: []
